[project]
name = "hello-agent"
version = "0.1.0"
description = "Hello-Agents learning notes and experiments"
readme = "README.md"
authors = [
    { name = "WenHao YAN", email = "howe8943@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=3.3.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tavily-python>=0.8.0",
]

[project.scripts]
hello-agent = "hello_agent:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
